### ISSUE TITLE
Cannot read property 'initialise' of undefined

### ISSUE THREAD

**Issue by nicinabox** [kirkness/react-native-swift-socketio#1]
It seems [the initial SocketIO require](https://github.com/kirkness/react-native-swift-socketio/blob/master/index.js#L4) returns undefined causing [the initialization](https://github.com/kirkness/react-native-swift-socketio/blob/master/index.js#L39) to fail down the line.

I checked NativeModules and it doesn't appear to have a SocketIO key. Any ideas?

Using React Native 0.4.4.

**Comment by kirkness** [comment]
Hi Nic, Have you followed the install at the bottom of the readme? This would be the case if you don't have the files copied to your build phases + set the Objc bridging header. Hope this helps!

**Comment by nicinabox** [comment]
Huh okay. I did have trouble with one of the steps.

> Search for Objective-C Bridging Header

This row doesn't exist (maybe that's expected?). I tried adding it as a User Defined setting, but had to name it "Objective_C_Bridging_Header". Perhaps that's the issue?

**Comment by kirkness** [comment]
Ok - yes it should be there, if you go click your project on the left, select your project name from the 'targets', then build settings, hopefully it should be there?

![screen shot 2015-05-18 at 16 52 48](https://cloud.githubusercontent.com/assets/7248220/7684501/66421184-fd7e-11e4-8b33-111b957d0bb7.png)

**Comment by nicinabox** [comment]
I got nothin.

![screen shot 2015-05-18 at 10 57 05 am](https://cloud.githubusercontent.com/assets/246280/7684562/ad65b836-fd4c-11e4-88cc-c64ead554b6a.png)

**Comment by nicinabox** [comment]
If I add a new blank swift file it seems to trigger that, but not when I add the files to the project.

**Comment by kirkness** [comment]
Oh ok - and what if you add the RNSwiftSocketIO group to your CuraMessenger group as opposed to libraries?

**Comment by nicinabox** [comment]
Same thing.

**Comment by nicinabox** [comment]
Same thing.

**Comment by kirkness** [comment]
Ok as in its not adding the field when you move them to your project? Also worth double checking all the RNSwiftSocketIO files are in your Compile Sources

**Comment by nicinabox** [comment]
Correct.

There was nothing in Compile Sources aside from AppDelegate.m and main.m, so attempting to add the directory there gives this: 

![screen shot 2015-05-18 at 11 13 12 am](https://cloud.githubusercontent.com/assets/246280/7684857/0b9d772a-fd4f-11e4-9cd4-b5756e6ca431.png)

It doesn't appear to have any children, but lets me add the directory anyway. Object-C Bridging Header still not available though.

**Comment by kirkness** [comment]
Interesting - I think it may be worth removing the files and running through the install again. I think that the problem will have stemmed from originally adding the group to libraries rather than the main package. Let me know if you have any luck.

**Comment by nicinabox** [comment]
Just tried with a newly generated project (`react-native init ...`) and see the same thing. Seems like it never recognizes the swift files.

**Comment by kirkness** [comment]
Hmm - the only other thing that I can see effects it is if you change the settings on here:

![screen shot 2015-05-18 at 17 36 36](https://cloud.githubusercontent.com/assets/7248220/7685241/aaa2ebc2-fd84-11e4-9c82-aae2732ca3e4.png)

(If just creating references it fails)

**Comment by nicinabox** [comment]
AH! That changes things.

I get all the swift files in Compile Sources and the Objective-C Bridging Header option. 

Nice work!

**Comment by kirkness** [comment]
Awesome - cheers mate!

**Comment by nicinabox** [comment]
Thanks for your help @kirkness!
