### ISSUE TITLE
Attempting to use with React Native 0.6.0-rc

### ISSUE THREAD

**Issue by nicinabox** [kirkness/react-native-swift-socketio#2]
Perhaps I should stay off the RC, but I thought I should let you know about this anyway. There are a couple of issues.

> Unknown argument type 'NSObject' in method -[SocketIO emit:items:]. Extend RCTConvert to support this type.

and 

> SocketIO.emit was called with 2 arguments, but expects 1

I suspect the first might clear up the latter? Might be related to [this line](https://github.com/kirkness/react-native-swift-socketio/blob/master/RNSwiftSocketIO/SocketBridge.m#L18)?

**Comment by kirkness** [comment]
Thanks Nic, yes sounds like a small issue. I wont have the time to look properly in to this for the next week so feel free to pull request if you find the fix! Cheers

**Comment by kirkness** [comment]
Cheer Nic!
